<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net48;netstandard2.0;netstandard2.1;netcoreapp3.1;net6.0;net7.0;net8.0;net9.0</TargetFrameworks>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<LangVersion>10</LangVersion>
		<NuspecFile>Thunderbolt.Extensions.DependencyInjection.nuspec</NuspecFile>
		<NuspecProperties>
			id=$(MSBuildProjectName);
			version=$(Version);
			authors=$(Authors);
			owners=$(Owners);
		</NuspecProperties>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
	</PropertyGroup>

	<ItemGroup>
		<Using Remove="System.IO" />
		<Using Remove="System.Linq" />
		<Using Remove="System.Net.Http" />
	</ItemGroup>
</Project>
